### ISSUE TITLE
Write formal test case and test activity diagram

### ISSUE THREAD

**Issue by j-hermann** [OSC-CSC480SP16/roots-qa#17]

**Comment by RobertCurran** [comment]
http://localhost:1337/password_reset.html
is a blank page

**Comment by justinmaccreery** [comment]
I've created some equivalence diagrams and branch coverage tests (on paper) for Sign-up, Login and create Profile. Haven't completed and reported on tests though.

**Comment by justinmaccreery** [comment]
took 1 1/2 hours to generate the 4 equivalence classes and branch tests. They've been uploaded to github.
